# Simple Dockerfile
# Used by `pack` command as a base for build image
# when --use-docker option is specified

# The base image must be centos:8
FROM centos:8

# Here you can install some packages required
#   for your application build

# RUN set -x \
#    && curl -sL https://rpm.nodesource.com/setup_10.x | bash - \
#    && yum -y install nodejs
