$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
ignoreWords:
  - binl
  - chunkname
  - coro
  - decdpun
  - decinf
  - decnan
  - decneg
  - decnumdigits
  - decnummaxe
  - decnumunits
  - decpminus
  - decpminusalt
  - decpowers
  - decsnan
  - decspecial
  - dualnum
  - executinig
  - extl
  - frname
  - ftsz
  - gclen
  - gclistlen
  - gcnext
  - gcptr
  - gcref
  - gcringlen
  - gcval
  - gcvmask
  - glref
  - grayagain
  - hmask
  - hnode
  - hpart
  - islua
  - ispcall
  - lfunc
  - libluajit
  - lightud
  - lightudlo
  - lightudseg
  - ljgc
  - lsms
  - lstate
  - luap
  - memeq
  - mmudata
  - mslab
  - msudigits
  - nextgc
  - notu
  - pcallh
  - prevd
  - prevl
  - snprint
  - stepmul
  - streq
  - strl
  - sweepstr
  - sweepstring
  - tisnum
  - tlightud
  - tnumx
  - tudata
  - tvislightud
  - vdbe
  - vmstate
  - xrow
