name: "Prepare test environment with Tarantool EE"
description: "Prepares test environment with Tarantool EE"

inputs:
  sdk-version:
    required: true
    type: string
  sdk-build:
    required: false
    type: string
    default: release
  sdk-gc:
    required: false
    type: string
    default: gc64
  sdk-download-token:
    required: true
    type: string
  skip-etcd-install:
    description: Whether to skip etcd installation
    type: boolean
    required: false
    default: false

env:
  # Note: Use exactly match version of tool, to avoid unexpected issues with test on CI.
  GO_VERSION: '1.23.8'

runs:
  using: "composite"
  steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '${{ env.PYTHON_VERSION }}'

      - name: Setup Mage
        run: |
          git clone https://github.com/magefile/mage
          cd mage
          go run bootstrap.go
        shell: bash

      - name: Install build requirements
        run: |
          sudo apt -y update
          sudo apt -y install git gcc make cmake unzip zip fish zsh
        shell: bash

      - name: Cache Tarantool SDK
        id: cache-sdk
        uses: actions/cache@v3
        with:
          path: tarantool-enterprise
          key: ${{ matrix.sdk-version }}

      - name: Download Tarantool SDK
        run: |
          ARCHIVE_NAME=tarantool-enterprise-sdk-${{ inputs.sdk-gc }}-${{ inputs.sdk-version }}.tar.gz
          ARCHIVE_PATH=$(echo ${{ inputs.sdk-version }} | sed -rn \
            's/^([0-9]+)\.([0-9]+)\.([0-9]+-){2}([a-z0-9]+-)?r[0-9]+\.([a-z]+)\.([a-z0-9_]+)$/${{ inputs.sdk-build }}\/\5\/\6\/\1\.\2/p')
          curl -O -L \
            https://tarantool:${{ inputs.sdk-download-token }}@download.tarantool.io/enterprise/${ARCHIVE_PATH}/${ARCHIVE_NAME}
          tar -xzf ${ARCHIVE_NAME}
          rm -f ${ARCHIVE_NAME}
          source tarantool-enterprise/env.sh
        shell: bash

      - name: Install tarantool headers
        run: |
          INCLUDE_DIR=$(./tarantool-enterprise/tarantool --version | gawk \
            '/DCMAKE_INSTALL_PREFIX/ {dir=gensub(/.*-DCMAKE_INSTALL_PREFIX=(\/.*) .*/, "\\1", "g", $0);  print dir}')
          sudo mkdir -p ${INCLUDE_DIR}/include
          sudo cp -r tarantool-enterprise/include/tarantool ${INCLUDE_DIR}/include
        shell: bash

      - name: Add SDK to PATH and set TARANTOOL_SDK_PATH variable
        run: |
          SDK_PATH="$(realpath tarantool-enterprise)"
          echo "${SDK_PATH}" >> ${GITHUB_PATH}
          echo "TARANTOOL_SDK_PATH=${SDK_PATH}" >> ${GITHUB_ENV}
        shell: bash

      - name: Install etcd
        uses: ./.github/actions/setup-etcd
        if: ${{ inputs.skip-etcd-install == 'false' }}

      - name: Build tt
        env:
          TT_CLI_BUILD_SSL: 'static'
        run: mage build
        shell: bash

      - name: Install test requirements
        run: |
          sudo apt -y install gdb
          pip3 install -r test/requirements.txt
        shell: bash
