[general]
debug = true
regex-style-search = true

[ignore-by-title]
regex = ^build\(deps\):.*dependabot\[bot\]$
ignore = title-max-length,body-min-length

[ignore-by-author-name]
regex=^TarantoolBot(.*)
ignore=all

[title-min-length]
min-length=12

[title-max-length]
line-length = 50

[title-match-regex]
; Allows following subjects like:
; - "module: at least three words description"
; - "module1/module2: three words info"
; - "Release v1.2.3"
regex = ^(?:[\w\/-]+: (?:\S+ ){2,}\S+.*?|Release\s+v?\d+\.\d+\.\d)$

[body-min-length]
; Note: to allow almost empty commit body with single text: "Closes #123"
min-length=10

[body-max-line-length]
line-length = 72

[body-match-regex:reference_task_id]
; Task ID can be in digital format as "#123" (github task) or "ABC-123" (external task).
; NOTE: External task ID starts with letter, there should be no number sign (#) at the beginning.
; Allows following reference like:
; - Closes #123
; - Fixes #123, #456
; - Related to #123
; - Part of #123
; - Needed for #123
; - Follows TNTP-7060, TNTP-7061, TNTP-7062
regex = (?m)^(?:Closes|Fixes|Related to|Part of|Needed for|Follows) (?:(?:\w+/\w+)?#|[A-Z]+-)\d+(?:, (?:(?:\w+/\w+)?#|[A-Z]+-)?\d+)*$
