// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: aeon_router.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AeonRouterService_Ping_FullMethodName        = "/aeon_router.AeonRouterService/Ping"
	AeonRouterService_CreateSpace_FullMethodName = "/aeon_router.AeonRouterService/CreateSpace"
	AeonRouterService_DropSpace_FullMethodName   = "/aeon_router.AeonRouterService/DropSpace"
	AeonRouterService_Execute_FullMethodName     = "/aeon_router.AeonRouterService/Execute"
	AeonRouterService_Insert_FullMethodName      = "/aeon_router.AeonRouterService/Insert"
	AeonRouterService_Replace_FullMethodName     = "/aeon_router.AeonRouterService/Replace"
	AeonRouterService_Delete_FullMethodName      = "/aeon_router.AeonRouterService/Delete"
	AeonRouterService_Get_FullMethodName         = "/aeon_router.AeonRouterService/Get"
	AeonRouterService_Select_FullMethodName      = "/aeon_router.AeonRouterService/Select"
	AeonRouterService_SQL_FullMethodName         = "/aeon_router.AeonRouterService/SQL"
	AeonRouterService_SQLStream_FullMethodName   = "/aeon_router.AeonRouterService/SQLStream"
	AeonRouterService_SQLCheck_FullMethodName    = "/aeon_router.AeonRouterService/SQLCheck"
)

// AeonRouterServiceClient is the client API for AeonRouterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// API to Aeon - a distributed database based on Tarantool.
type AeonRouterServiceClient interface {
	// Pings the router.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Creates a space with the given definition.
	CreateSpace(ctx context.Context, in *CreateSpaceRequest, opts ...grpc.CallOption) (*CreateSpaceResponse, error)
	// Drops a space by name.
	DropSpace(ctx context.Context, in *DropSpaceRequest, opts ...grpc.CallOption) (*DropSpaceResponse, error)
	// Transactionally executes a set of read and write operations.
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	// Transactionally inserts tuples into a space.
	// Raises an error if a tuple with the same key already exists.
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	// Transactionally replaces tuples in a space.
	// If a tuple with the same key already exists, it will be replaced.
	Replace(ctx context.Context, in *ReplaceRequest, opts ...grpc.CallOption) (*ReplaceResponse, error)
	// Transactionally deletes tuples from a space.
	// If a key doesn't exist, it will be ignored (no error is raised).
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Transactionally queries tuples from a space.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// Non-transactionally select tuples from a space.
	Select(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SelectResponse], error)
	// Execute a SQL query.
	SQL(ctx context.Context, in *SQLRequest, opts ...grpc.CallOption) (*SQLResponse, error)
	// Execute a SQL query and return the result using a stream.
	SQLStream(ctx context.Context, in *SQLRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SQLResponse], error)
	// Check if an SQL is valid
	// We provide the method for database CLI.
	SQLCheck(ctx context.Context, in *SQLRequest, opts ...grpc.CallOption) (*SQLCheckResponse, error)
}

type aeonRouterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAeonRouterServiceClient(cc grpc.ClientConnInterface) AeonRouterServiceClient {
	return &aeonRouterServiceClient{cc}
}

func (c *aeonRouterServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, AeonRouterService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeonRouterServiceClient) CreateSpace(ctx context.Context, in *CreateSpaceRequest, opts ...grpc.CallOption) (*CreateSpaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSpaceResponse)
	err := c.cc.Invoke(ctx, AeonRouterService_CreateSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeonRouterServiceClient) DropSpace(ctx context.Context, in *DropSpaceRequest, opts ...grpc.CallOption) (*DropSpaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropSpaceResponse)
	err := c.cc.Invoke(ctx, AeonRouterService_DropSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeonRouterServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, AeonRouterService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeonRouterServiceClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, AeonRouterService_Insert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeonRouterServiceClient) Replace(ctx context.Context, in *ReplaceRequest, opts ...grpc.CallOption) (*ReplaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplaceResponse)
	err := c.cc.Invoke(ctx, AeonRouterService_Replace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeonRouterServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, AeonRouterService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeonRouterServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, AeonRouterService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeonRouterServiceClient) Select(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SelectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AeonRouterService_ServiceDesc.Streams[0], AeonRouterService_Select_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SelectRequest, SelectResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AeonRouterService_SelectClient = grpc.ServerStreamingClient[SelectResponse]

func (c *aeonRouterServiceClient) SQL(ctx context.Context, in *SQLRequest, opts ...grpc.CallOption) (*SQLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SQLResponse)
	err := c.cc.Invoke(ctx, AeonRouterService_SQL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeonRouterServiceClient) SQLStream(ctx context.Context, in *SQLRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SQLResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AeonRouterService_ServiceDesc.Streams[1], AeonRouterService_SQLStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SQLRequest, SQLResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AeonRouterService_SQLStreamClient = grpc.ServerStreamingClient[SQLResponse]

func (c *aeonRouterServiceClient) SQLCheck(ctx context.Context, in *SQLRequest, opts ...grpc.CallOption) (*SQLCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SQLCheckResponse)
	err := c.cc.Invoke(ctx, AeonRouterService_SQLCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AeonRouterServiceServer is the server API for AeonRouterService service.
// All implementations must embed UnimplementedAeonRouterServiceServer
// for forward compatibility.
//
// API to Aeon - a distributed database based on Tarantool.
type AeonRouterServiceServer interface {
	// Pings the router.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Creates a space with the given definition.
	CreateSpace(context.Context, *CreateSpaceRequest) (*CreateSpaceResponse, error)
	// Drops a space by name.
	DropSpace(context.Context, *DropSpaceRequest) (*DropSpaceResponse, error)
	// Transactionally executes a set of read and write operations.
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	// Transactionally inserts tuples into a space.
	// Raises an error if a tuple with the same key already exists.
	Insert(context.Context, *InsertRequest) (*InsertResponse, error)
	// Transactionally replaces tuples in a space.
	// If a tuple with the same key already exists, it will be replaced.
	Replace(context.Context, *ReplaceRequest) (*ReplaceResponse, error)
	// Transactionally deletes tuples from a space.
	// If a key doesn't exist, it will be ignored (no error is raised).
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// Transactionally queries tuples from a space.
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// Non-transactionally select tuples from a space.
	Select(*SelectRequest, grpc.ServerStreamingServer[SelectResponse]) error
	// Execute a SQL query.
	SQL(context.Context, *SQLRequest) (*SQLResponse, error)
	// Execute a SQL query and return the result using a stream.
	SQLStream(*SQLRequest, grpc.ServerStreamingServer[SQLResponse]) error
	// Check if an SQL is valid
	// We provide the method for database CLI.
	SQLCheck(context.Context, *SQLRequest) (*SQLCheckResponse, error)
	mustEmbedUnimplementedAeonRouterServiceServer()
}

// UnimplementedAeonRouterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAeonRouterServiceServer struct{}

func (UnimplementedAeonRouterServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAeonRouterServiceServer) CreateSpace(context.Context, *CreateSpaceRequest) (*CreateSpaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSpace not implemented")
}
func (UnimplementedAeonRouterServiceServer) DropSpace(context.Context, *DropSpaceRequest) (*DropSpaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropSpace not implemented")
}
func (UnimplementedAeonRouterServiceServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedAeonRouterServiceServer) Insert(context.Context, *InsertRequest) (*InsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedAeonRouterServiceServer) Replace(context.Context, *ReplaceRequest) (*ReplaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Replace not implemented")
}
func (UnimplementedAeonRouterServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAeonRouterServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAeonRouterServiceServer) Select(*SelectRequest, grpc.ServerStreamingServer[SelectResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Select not implemented")
}
func (UnimplementedAeonRouterServiceServer) SQL(context.Context, *SQLRequest) (*SQLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SQL not implemented")
}
func (UnimplementedAeonRouterServiceServer) SQLStream(*SQLRequest, grpc.ServerStreamingServer[SQLResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SQLStream not implemented")
}
func (UnimplementedAeonRouterServiceServer) SQLCheck(context.Context, *SQLRequest) (*SQLCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SQLCheck not implemented")
}
func (UnimplementedAeonRouterServiceServer) mustEmbedUnimplementedAeonRouterServiceServer() {}
func (UnimplementedAeonRouterServiceServer) testEmbeddedByValue()                           {}

// UnsafeAeonRouterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AeonRouterServiceServer will
// result in compilation errors.
type UnsafeAeonRouterServiceServer interface {
	mustEmbedUnimplementedAeonRouterServiceServer()
}

func RegisterAeonRouterServiceServer(s grpc.ServiceRegistrar, srv AeonRouterServiceServer) {
	// If the following call pancis, it indicates UnimplementedAeonRouterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AeonRouterService_ServiceDesc, srv)
}

func _AeonRouterService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeonRouterServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeonRouterService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeonRouterServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeonRouterService_CreateSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeonRouterServiceServer).CreateSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeonRouterService_CreateSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeonRouterServiceServer).CreateSpace(ctx, req.(*CreateSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeonRouterService_DropSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeonRouterServiceServer).DropSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeonRouterService_DropSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeonRouterServiceServer).DropSpace(ctx, req.(*DropSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeonRouterService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeonRouterServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeonRouterService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeonRouterServiceServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeonRouterService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeonRouterServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeonRouterService_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeonRouterServiceServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeonRouterService_Replace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeonRouterServiceServer).Replace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeonRouterService_Replace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeonRouterServiceServer).Replace(ctx, req.(*ReplaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeonRouterService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeonRouterServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeonRouterService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeonRouterServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeonRouterService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeonRouterServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeonRouterService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeonRouterServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeonRouterService_Select_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SelectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AeonRouterServiceServer).Select(m, &grpc.GenericServerStream[SelectRequest, SelectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AeonRouterService_SelectServer = grpc.ServerStreamingServer[SelectResponse]

func _AeonRouterService_SQL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SQLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeonRouterServiceServer).SQL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeonRouterService_SQL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeonRouterServiceServer).SQL(ctx, req.(*SQLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeonRouterService_SQLStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SQLRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AeonRouterServiceServer).SQLStream(m, &grpc.GenericServerStream[SQLRequest, SQLResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AeonRouterService_SQLStreamServer = grpc.ServerStreamingServer[SQLResponse]

func _AeonRouterService_SQLCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SQLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeonRouterServiceServer).SQLCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeonRouterService_SQLCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeonRouterServiceServer).SQLCheck(ctx, req.(*SQLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AeonRouterService_ServiceDesc is the grpc.ServiceDesc for AeonRouterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AeonRouterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aeon_router.AeonRouterService",
	HandlerType: (*AeonRouterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _AeonRouterService_Ping_Handler,
		},
		{
			MethodName: "CreateSpace",
			Handler:    _AeonRouterService_CreateSpace_Handler,
		},
		{
			MethodName: "DropSpace",
			Handler:    _AeonRouterService_DropSpace_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _AeonRouterService_Execute_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _AeonRouterService_Insert_Handler,
		},
		{
			MethodName: "Replace",
			Handler:    _AeonRouterService_Replace_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AeonRouterService_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AeonRouterService_Get_Handler,
		},
		{
			MethodName: "SQL",
			Handler:    _AeonRouterService_SQL_Handler,
		},
		{
			MethodName: "SQLCheck",
			Handler:    _AeonRouterService_SQLCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Select",
			Handler:       _AeonRouterService_Select_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SQLStream",
			Handler:       _AeonRouterService_SQLStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "aeon_router.proto",
}
