// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.28.3
// source: aeon_ddl.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSpaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the new space.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Format of the new space.
	Format []*FieldDef `protobuf:"bytes,2,rep,name=format,proto3" json:"format,omitempty"`
	// Sorting key definition (indexed fields).
	KeyDef        []*KeyPartDef `protobuf:"bytes,3,rep,name=key_def,json=keyDef,proto3" json:"key_def,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSpaceRequest) Reset() {
	*x = CreateSpaceRequest{}
	mi := &file_aeon_ddl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpaceRequest) ProtoMessage() {}

func (x *CreateSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aeon_ddl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpaceRequest.ProtoReflect.Descriptor instead.
func (*CreateSpaceRequest) Descriptor() ([]byte, []int) {
	return file_aeon_ddl_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSpaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSpaceRequest) GetFormat() []*FieldDef {
	if x != nil {
		return x.Format
	}
	return nil
}

func (x *CreateSpaceRequest) GetKeyDef() []*KeyPartDef {
	if x != nil {
		return x.KeyDef
	}
	return nil
}

type CreateSpaceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error information. Set only on failure.
	Error         *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSpaceResponse) Reset() {
	*x = CreateSpaceResponse{}
	mi := &file_aeon_ddl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSpaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpaceResponse) ProtoMessage() {}

func (x *CreateSpaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aeon_ddl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpaceResponse.ProtoReflect.Descriptor instead.
func (*CreateSpaceResponse) Descriptor() ([]byte, []int) {
	return file_aeon_ddl_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSpaceResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DropSpaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the space to drop.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropSpaceRequest) Reset() {
	*x = DropSpaceRequest{}
	mi := &file_aeon_ddl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropSpaceRequest) ProtoMessage() {}

func (x *DropSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aeon_ddl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropSpaceRequest.ProtoReflect.Descriptor instead.
func (*DropSpaceRequest) Descriptor() ([]byte, []int) {
	return file_aeon_ddl_proto_rawDescGZIP(), []int{2}
}

func (x *DropSpaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DropSpaceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error information. Set only on failure.
	Error         *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropSpaceResponse) Reset() {
	*x = DropSpaceResponse{}
	mi := &file_aeon_ddl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropSpaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropSpaceResponse) ProtoMessage() {}

func (x *DropSpaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aeon_ddl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropSpaceResponse.ProtoReflect.Descriptor instead.
func (*DropSpaceResponse) Descriptor() ([]byte, []int) {
	return file_aeon_ddl_proto_rawDescGZIP(), []int{3}
}

func (x *DropSpaceResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_aeon_ddl_proto protoreflect.FileDescriptor

var file_aeon_ddl_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x65, 0x6f, 0x6e, 0x5f, 0x64, 0x64, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x61, 0x65, 0x6f, 0x6e, 0x1a, 0x10, 0x61, 0x65, 0x6f, 0x6e, 0x5f, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x61, 0x65, 0x6f, 0x6e, 0x5f, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x12, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x65, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x44, 0x65, 0x66, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x29, 0x0a,
	0x07, 0x6b, 0x65, 0x79, 0x5f, 0x64, 0x65, 0x66, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x61, 0x65, 0x6f, 0x6e, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x72, 0x74, 0x44, 0x65, 0x66,
	0x52, 0x06, 0x6b, 0x65, 0x79, 0x44, 0x65, 0x66, 0x22, 0x38, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x21, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x61, 0x65, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x26, 0x0a, 0x10, 0x44, 0x72, 0x6f, 0x70, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x36, 0x0a, 0x11, 0x44, 0x72,
	0x6f, 0x70, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x21, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x61, 0x65, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x32, 0x92, 0x01, 0x0a, 0x0a, 0x44, 0x44, 0x4c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x44, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x12, 0x18, 0x2e, 0x61, 0x65, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x65, 0x6f,
	0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x09, 0x44, 0x72, 0x6f, 0x70, 0x53,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x16, 0x2e, 0x61, 0x65, 0x6f, 0x6e, 0x2e, 0x44, 0x72, 0x6f, 0x70,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61,
	0x65, 0x6f, 0x6e, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aeon_ddl_proto_rawDescOnce sync.Once
	file_aeon_ddl_proto_rawDescData = file_aeon_ddl_proto_rawDesc
)

func file_aeon_ddl_proto_rawDescGZIP() []byte {
	file_aeon_ddl_proto_rawDescOnce.Do(func() {
		file_aeon_ddl_proto_rawDescData = protoimpl.X.CompressGZIP(file_aeon_ddl_proto_rawDescData)
	})
	return file_aeon_ddl_proto_rawDescData
}

var file_aeon_ddl_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_aeon_ddl_proto_goTypes = []any{
	(*CreateSpaceRequest)(nil),  // 0: aeon.CreateSpaceRequest
	(*CreateSpaceResponse)(nil), // 1: aeon.CreateSpaceResponse
	(*DropSpaceRequest)(nil),    // 2: aeon.DropSpaceRequest
	(*DropSpaceResponse)(nil),   // 3: aeon.DropSpaceResponse
	(*FieldDef)(nil),            // 4: aeon.FieldDef
	(*KeyPartDef)(nil),          // 5: aeon.KeyPartDef
	(*Error)(nil),               // 6: aeon.Error
}
var file_aeon_ddl_proto_depIdxs = []int32{
	4, // 0: aeon.CreateSpaceRequest.format:type_name -> aeon.FieldDef
	5, // 1: aeon.CreateSpaceRequest.key_def:type_name -> aeon.KeyPartDef
	6, // 2: aeon.CreateSpaceResponse.error:type_name -> aeon.Error
	6, // 3: aeon.DropSpaceResponse.error:type_name -> aeon.Error
	0, // 4: aeon.DDLService.CreateSpace:input_type -> aeon.CreateSpaceRequest
	2, // 5: aeon.DDLService.DropSpace:input_type -> aeon.DropSpaceRequest
	1, // 6: aeon.DDLService.CreateSpace:output_type -> aeon.CreateSpaceResponse
	3, // 7: aeon.DDLService.DropSpace:output_type -> aeon.DropSpaceResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_aeon_ddl_proto_init() }
func file_aeon_ddl_proto_init() {
	if File_aeon_ddl_proto != nil {
		return
	}
	file_aeon_error_proto_init()
	file_aeon_schema_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aeon_ddl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aeon_ddl_proto_goTypes,
		DependencyIndexes: file_aeon_ddl_proto_depIdxs,
		MessageInfos:      file_aeon_ddl_proto_msgTypes,
	}.Build()
	File_aeon_ddl_proto = out.File
	file_aeon_ddl_proto_rawDesc = nil
	file_aeon_ddl_proto_goTypes = nil
	file_aeon_ddl_proto_depIdxs = nil
}
