// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: aeon_diag.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiagService_Ping_FullMethodName = "/aeon.DiagService/Ping"
)

// DiagServiceClient is the client API for DiagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Diagnostic API to Aeon - a distributed database based on Tarantool.
type DiagServiceClient interface {
	// Pings the router.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type diagServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiagServiceClient(cc grpc.ClientConnInterface) DiagServiceClient {
	return &diagServiceClient{cc}
}

func (c *diagServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, DiagService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiagServiceServer is the server API for DiagService service.
// All implementations must embed UnimplementedDiagServiceServer
// for forward compatibility.
//
// Diagnostic API to Aeon - a distributed database based on Tarantool.
type DiagServiceServer interface {
	// Pings the router.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedDiagServiceServer()
}

// UnimplementedDiagServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiagServiceServer struct{}

func (UnimplementedDiagServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDiagServiceServer) mustEmbedUnimplementedDiagServiceServer() {}
func (UnimplementedDiagServiceServer) testEmbeddedByValue()                     {}

// UnsafeDiagServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiagServiceServer will
// result in compilation errors.
type UnsafeDiagServiceServer interface {
	mustEmbedUnimplementedDiagServiceServer()
}

func RegisterDiagServiceServer(s grpc.ServiceRegistrar, srv DiagServiceServer) {
	// If the following call pancis, it indicates UnimplementedDiagServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiagService_ServiceDesc, srv)
}

func _DiagService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiagService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiagService_ServiceDesc is the grpc.ServiceDesc for DiagService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiagService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aeon.DiagService",
	HandlerType: (*DiagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _DiagService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aeon_diag.proto",
}
