// Code generated by "stringer -type=ElectionMode -trimprefix ElectionMode -linecomment"; DO NOT EDIT.

package replicaset

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ElectionModeUnknown-0]
	_ = x[ElectionModeOff-1]
	_ = x[ElectionModeVoter-2]
	_ = x[ElectionModeCandidate-3]
	_ = x[ElectionModeManual-4]
}

const _ElectionMode_name = "unknownoffvotercandidatemanual"

var _ElectionMode_index = [...]uint8{0, 7, 10, 15, 24, 30}

func (i ElectionMode) String() string {
	if i < 0 || i >= ElectionMode(len(_ElectionMode_index)-1) {
		return "ElectionMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ElectionMode_name[_ElectionMode_index[i]:_ElectionMode_index[i+1]]
}
