// Code generated by "stringer -type=Failover -trimprefix Failover -linecomment"; DO NOT EDIT.

package replicaset

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FailoverUnknown-0]
	_ = x[FailoverOff-1]
	_ = x[FailoverManual-2]
	_ = x[FailoverEventual-3]
	_ = x[FailoverElection-4]
	_ = x[FailoverStateful-5]
	_ = x[FailoverSupervised-6]
}

const _Failover_name = "unknownoffmanualeventualelectionstatefulsupervised" // spell-checker:disable-line

var _Failover_index = [...]uint8{0, 7, 10, 16, 24, 32, 40, 50}

func (i Failover) String() string {
	if i < 0 || i >= Failover(len(_Failover_index)-1) {
		return "Failover(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Failover_name[_Failover_index[i]:_Failover_index[i+1]]
}
