// Code generated by "stringer -type=Failover -trimprefix Failover -linecomment"; DO NOT EDIT.

package replicaset

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FailoverUnknown-0]
	_ = x[FailoverOff-1]
	_ = x[FailoverManual-2]
	_ = x[FailoverElection-3]
	_ = x[FailoverSupervised-4]
}

const _Failover_name = "unknownoffmanualelectionsupervised"

var _Failover_index = [...]uint8{0, 7, 10, 16, 24, 34}

func (i Failover) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Failover_index)-1 {
		return "Failover(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Failover_name[_Failover_index[idx]:_Failover_index[idx+1]]
}
