// Code generated by "stringer -type=Master -trimprefix Master -linecomment"; DO NOT EDIT.

package replicaset

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MasterUnknown-0]
	_ = x[MasterNo-1]
	_ = x[MasterSingle-2]
	_ = x[MasterMulti-3]
}

const _Master_name = "unknownnosinglemulti" // spell-checker:disable-line

var _Master_index = [...]uint8{0, 7, 9, 15, 20}

func (i Master) String() string {
	if i < 0 || i >= Master(len(_Master_index)-1) {
		return "Master(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Master_name[_Master_index[i]:_Master_index[i+1]]
}
