// Code generated by "stringer -type=Orchestrator -trimprefix Orchestrator -linecomment"; DO NOT EDIT.

package replicaset

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OrchestratorUnknown-0]
	_ = x[OrchestratorCentralizedConfig-1]
	_ = x[OrchestratorCartridge-2]
	_ = x[OrchestratorCustom-3]
}

const _Orchestrator_name = "unknowncentralized configcartridgecustom"

var _Orchestrator_index = [...]uint8{0, 7, 25, 34, 40}

func (i Orchestrator) String() string {
	if i < 0 || i >= Orchestrator(len(_Orchestrator_index)-1) {
		return "Orchestrator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Orchestrator_name[_Orchestrator_index[i]:_Orchestrator_index[i+1]]
}
