// Code generated by "stringer -type=State -trimprefix State -linecomment"; DO NOT EDIT.

package replicaset

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateUnknown-0]
	_ = x[StateUninitialized-1]
	_ = x[StateBootstrapped-2]
}

const _State_name = "unknownuninitializedbootstrapped"

var _State_index = [...]uint8{0, 7, 20, 32}

func (i State) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_State_index)-1 {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[idx]:_State_index[idx+1]]
}
