#!/usr/bin/env tarantool

local instance_config = require('internal.config.instance_config')
local fio = require('fio')

local file = fio.open("envpaths.go", {'O_WRONLY', 'O_CREAT'})
file:write(string.format([[// Code generated by env_generate.lua; DO NOT EDIT.
// Tarantool version: %s
//
// To update the file:
// 1. Install a latest Tarantool version.
// 2. Run: go generate ./...

package cluster

var ConfigEnvPaths = [][]string{
]], box.info.version))

for _, w in instance_config:pairs() do
    file:write('\t[]string{')
    for i, v in ipairs(w.path) do
       file:write('"' .. v .. '"')
       if i < #w.path then
           file:write(", ")
       end
    end
    file:write('},\n')
end

file:write('}\n')
file:close()
