name: "Prepare test environment with Tarantool CE"
description: "Prepares test environment with Tarantool CE"

inputs:
  tarantool-version:
    required: true
    type: string
  skip-tarantool-install:
    description: Whether to skip tarantool installation
    type: boolean
    required: false
    default: false
  skip-etcd-install:
    description: Whether to skip etcd installation
    type: boolean
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '${{ env.GO_VERSION }}'

    - name: Setup Mage
      run: |
        git clone https://github.com/magefile/mage
        cd mage
        go run bootstrap.go
      shell: bash

    - name: Install build requirements
      run: |
        sudo apt -y update
        sudo apt -y install git gcc make cmake unzip zip
        sudo apt-get --allow-releaseinfo-change update
        sudo apt-get -y -f install \
        build-essential ninja-build \
        lua5.1 luarocks lcov \
        ruby-dev liblz4-dev  autoconf \
        automake \
        libtool python3-pytest python3-psutil pip
        sudo luarocks install luacheck 0.26.1
        sudo gem install coveralls-lcov
        sudo pip3 install tarantool
      shell: bash

    - name: Install Tarantool
      if: |
        inputs.skip-tarantool-install == 'false' &&
        !startsWith(inputs.tarantool-version, '3.')
      uses: tarantool/setup-tarantool@v1
      with:
        tarantool-version: '${{ inputs.tarantool-version }}'

    # Here is a workaround for Tarantool 3.0 installation until it is supported
    # by setup-tarantool. This step will install the latest pre-released
    # Tarantool 3.0 from repository.
    - name: Install Tarantool from repo
      if: |
        inputs.skip-tarantool-install == 'false' &&
        startsWith(inputs.tarantool-version, '3.')
      run: |
        sudo curl -L https://tarantool.io/iqJapRm/release/3/installer.sh | \
        sed 's|repo_type="release"|repo_type="pre-release"|' | bash
        sudo apt install tarantool tarantool-dev
      shell: bash

    - name: Install etcd
      uses: ./.github/actions/setup-etcd
      if: ${{ inputs.skip-etcd-install == 'false' }}

    - name: Build tt
      env:
        TT_CLI_BUILD_SSL: 'static'
      run: mage build
      shell: bash
