name: "Run static code check"
description: "Performs static code checks."

runs:
  using: "composite"
  steps:
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install tests requirements
        run: |
          pip3 install -r test/requirements.txt
        shell: bash

      - name: Log versions
        run: |
          go version
          mage --version
          tarantool --version
          rpm --version
        shell: bash

      - name: Codespell checks
        run: mage codespell
        shell: bash

      - name: License checker
        run: |
          go install github.com/uw-labs/lichen@latest
          mage checklicenses
        shell: bash

      - name: Go Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.63.4
          args: --config=golangci-lint.yml --out-${NO_FUTURE}format colored-line-number
          skip-cache: true

      - name: Python Linter
        run: python3 -m flake8 test
        shell: bash

