name: "Run static code check"
description: "Performs static code checks."

runs:
  using: "composite"
  steps:
    - name: Log versions
      run: |
        go version
        mage --version
        tarantool --version
        rpm --version
      shell: bash

    - name: License checker
      run: |
        go install github.com/uw-labs/lichen@latest
        mage checklicenses
      shell: bash

    - name: Find git base branch
      shell: bash
      run: |
        HASH=$(git log --format='%H^%D' | grep 'origin/' | head -n 2 | tail -n 1 | cut -f1 -d^)
        echo "Found base branch with hash: '${HASH}'"
        echo "BASE_BRANCH=${HASH}" >> ${GITHUB_ENV}

    - name: pre-commit checks (diff)
      uses: pre-commit/action@v3.0.1
      env:
        SKIP: golangci-lint-full
      with:
        extra_args: --all-files --from-ref=${{ env.BASE_BRANCH }} --to-ref=HEAD --hook-stage=manual

    - name: pre-commit checks (full)
      uses: pre-commit/action@v3.0.1
      env:
        SKIP: golangci-lint-diff
      with:
        extra_args: --all-files --hook-stage=manual
