FROM ubuntu:18.04

WORKDIR /work
RUN apt-get update && apt-get install -y git cmake make build-essential zlib1g-dev \
libreadline-dev libncurses5-dev libssl-dev libunwind-dev libicu-dev autoconf libtool
RUN chown {{.uid}} /work
COPY ./ ./
